

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JOptionPane;


public class addResource extends javax.swing.JFrame {

    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;

    /**
     * Creates new form Teacher
     */
    public addResource() {
        initComponents();
        con = databaseConnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        seats = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Claa_Num = new javax.swing.JTextField();
        numWht = new javax.swing.JTextField();
        numPro = new javax.swing.JTextField();
        numMar = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        newTeacher = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        mainmenu = new javax.swing.JButton();
        mainmenu1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seats.setBackground(new java.awt.Color(255, 102, 102));
        seats.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("ADD NEW Resources");
        seats.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Class Number");
        seats.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Number of white boards");
        seats.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("Number of Projecters");
        seats.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("Number of Markers");
        seats.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        Claa_Num.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seats.add(Claa_Num, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 217, 29));

        numWht.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        numWht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numWhtActionPerformed(evt);
            }
        });
        seats.add(numWht, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 217, 29));

        numPro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        numPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numProActionPerformed(evt);
            }
        });
        seats.add(numPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 217, 29));

        numMar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seats.add(numMar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 217, 29));

        search.setBackground(new java.awt.Color(255, 102, 102));
        search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        seats.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        newTeacher.setBackground(new java.awt.Color(255, 102, 102));
        newTeacher.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newTeacher.setForeground(new java.awt.Color(255, 255, 255));
        newTeacher.setText("NEW");
        newTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTeacherActionPerformed(evt);
            }
        });
        seats.add(newTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 88, -1));

        update.setBackground(new java.awt.Color(255, 102, 102));
        update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        seats.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        delete.setBackground(new java.awt.Color(255, 102, 102));
        delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        seats.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        mainmenu.setBackground(new java.awt.Color(255, 102, 102));
        mainmenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mainmenu.setForeground(new java.awt.Color(255, 255, 255));
        mainmenu.setText(" BACK");
        mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuActionPerformed(evt);
            }
        });
        seats.add(mainmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 100, -1));

        mainmenu1.setBackground(new java.awt.Color(255, 102, 102));
        mainmenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mainmenu1.setForeground(new java.awt.Color(255, 255, 255));
        mainmenu1.setText("MAIN MENU");
        mainmenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenu1ActionPerformed(evt);
            }
        });
        seats.add(mainmenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.gif"))); // NOI18N
        seats.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -10, 755, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(seats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:   
        try {
            stmt = con.createStatement();

            int sClsId = Integer.parseInt(Claa_Num.getText());

            String query = "SELECT * FROM allclassrooms";

            rs = stmt.executeQuery(query);

            while (rs.next()) {
                if (sClsId == rs.getInt("ClassNumber")) {
                    numWht.setText(rs.getString("White_Boards"));
                    numPro.setText(rs.getString("Projectors"));
                    numMar.setText(rs.getString("Markers"));

                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_searchActionPerformed

    public void Reset() {
        Claa_Num.setText("");
        numWht.setText("");
        numPro.setText("");
        numMar.setText("");

    }

    private void newTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTeacherActionPerformed
        // TODO add your handling code here:
        Reset();
    }//GEN-LAST:event_newTeacherActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try {
            stmt = con.createStatement();

            int sClsId = Integer.parseInt(Claa_Num.getText());
            int sNumseats = Integer.parseInt(Claa_Num.getText());
            int snumWht = Integer.parseInt(numWht.getText());
            int snumPro = Integer.parseInt(numPro.getText());
            int snumMar = Integer.parseInt(numMar.getText());

            String query = "UPDATE allclassrooms SET ClassNumber = ?, Number_of_Seats = ?, White_Boards = ?, Projectors = ?, Markers = ? WHERE ClassNumber = ?";

            PreparedStatement preparedStmt = con.prepareStatement(query);

            preparedStmt.setInt(1, sClsId);
            preparedStmt.setInt(2, sNumseats);
            preparedStmt.setInt(3, snumWht);
            preparedStmt.setInt(4, snumPro);
            preparedStmt.setInt(5, snumMar);
            preparedStmt.setInt(6, sClsId);

            preparedStmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "UPDATED");

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try {
            stmt = con.createStatement();

            int sClsId = Integer.parseInt(Claa_Num.getText());

            String query = "DELETE FROM allclassrooms WHERE ClassNumber ='" + sClsId + "' ";

            stmt.executeUpdate(query);

            Reset();
            JOptionPane.showMessageDialog(null, "DELETED");

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void mainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ResourceModule view = new ResourceModule();
        view.setVisible(true);
    }//GEN-LAST:event_mainmenuActionPerformed

    private void numWhtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numWhtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numWhtActionPerformed

    private void numProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numProActionPerformed

    private void mainmenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainmenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addClaasroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addClaasroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addClaasroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addClaasroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addResource().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Claa_Num;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton mainmenu;
    private javax.swing.JButton mainmenu1;
    private javax.swing.JButton newTeacher;
    private javax.swing.JTextField numMar;
    private javax.swing.JTextField numPro;
    private javax.swing.JTextField numWht;
    private javax.swing.JButton search;
    private javax.swing.JPanel seats;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
byte[] photo = null;
    String filename = null;

}
